### ISSUE TITLE
Player can bet negative amount

### ISSUE THREAD

**Issue by sparkyfen** [bradwestfall/blackjack.js#1]
![screen shot 2015-06-05 at 2 12 11 pm](https://cloud.githubusercontent.com/assets/1609870/7999796/eaca44be-0b8c-11e5-9816-fb41cdabe404.png)

**Comment by bradwestfall** [comment]
ha, I know I still need to work on it. I didn't know anyone was playing it. Actually after I fix a few little things like that the next step is to make it so an AI can be added to vet out a betting strategy.

**Comment by bradwestfall** [comment]
Did you like playing it though?

**Comment by sparkyfen** [comment]
Sounds good :) I enjoyed playing it! Was working on Blackjack myself but stumbled on to yours because I'm following you!

**Comment by bradwestfall** [comment]
Sweet. The whole real purpose is that I want to try various versions of a "progressive" betting strategy. I found myself playing android apps and doing well but it was taking a lot of time. So I thought I'd automate it. Plus depending on the android game I was playing, I would either do really poor or really well. I think those games are programmed with a motive so I just thought If I could make one I would know it would be objective. I need to add a pubsub pattern so the game announces it's state. Then an AI would listen in and play

**Comment by sparkyfen** [comment]
The idea sounds great! I'll keep a watch on it! :) Feel free to close this issue when the negative amount is fixed!

**Comment by bradwestfall** [comment]
will do, thanks for testing

**Comment by bradwestfall** [comment]
fixed
